project:
  type: website

website:
  title: "Arun Kumar"
  site-url: https://github.com/arunmhh
  description: "researcher and R/Python educator with a passion for youtube community"
  favicon: assets/2.png
  page-navigation: true
  back-to-top-navigation: true

  navbar:
    logo: assets/1.png
    tools:
      - icon: github
        href: https://www.github.com/arunmhh/
    right:
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: Blog
        aria-label: "Meeting People Where They R"
        href: blog/blog_index.qmd
      #- text: Talks
      #  aria-label: "Invited Talks"
      #  href: talk/index.qmd  
      - text: Publications
        aria-label: "Publications"
        href: publication/index.qmd
      - text: Projects
        aria-label: "Project Portfolio"
        href: project/index.qmd

  page-footer:  
    left: >-
      &#169; 2024 Arun Kumar &#8729; Made with [Quarto](https://quarto.org) Pwoderd by [github](https://github.com)

format: 
  html:
    theme:
      light:
        - cosmo
      dark: 
        - cosmo
        
    code-link: true
    pagetitle: "{{< meta title >}} | Arun Kumar"
    lightbox: true
    toc: true

editor: visual


